# Generated by Django 5.1.6 on 2025-03-01 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
