# Generated by Django 5.1.6 on 2025-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_subscription_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='landing_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
